[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/icon-192.png"
  to = "/icon-192.png"
  status = 200

[[redirects]]
  from = "/icon-512.png"
  to = "/icon-512.png"
  status = 200

[[redirects]]
  from = "/icon-512-maskable.png"
  to = "/icon-512-maskable.png"
  status = 200

[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200

[[redirects]]
  from = "/sw.js"
  to = "/sw.js"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://js.stripe.com https://cdn.onesignal.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; media-src 'self' https:; connect-src 'self' https://*.supabase.co https://api.stripe.com https://cdn.onesignal.com https://onesignal.com https://www.matermundi.tv; frame-src 'self' https://js.stripe.com https://www.youtube.com https://youtube.com; frame-ancestors 'self'"
